# Generated by Django 3.1.2 on 2020-10-21 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Questions',
            new_name='Question',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='optiona',
            new_name='option1',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='optionb',
            new_name='option2',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='optionc',
            new_name='option3',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='optiond',
            new_name='option4',
        ),
    ]
