# Generated by Django 3.1.2 on 2020-10-21 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0002_auto_20201021_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='option5',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
