# Generated by Django 3.1.2 on 2020-10-21 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0003_question_option5'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=100)),
                ('shortName', models.CharField(max_length=20)),
            ],
        ),
    ]
