# Generated by Django 3.1.2 on 2020-10-21 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0004_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='catagory',
            field=models.CharField(choices=[('sports', 'Sports'), ('movies', 'Movies'), ('maths', 'Maths'), ('generalknowledge', 'GeneralKnowledge')], max_length=20),
        ),
    ]
