# Generated by Django 3.1.2 on 2020-10-21 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0005_auto_20201022_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='catagory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exam.category'),
        ),
    ]
